[tool.poetry]
name = "fractal-analysis"
version = "0.1.1"
description = ""
authors = ["yujiading <yujia.ding@cgu.edu>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/yujiading/fractals"
repository = "https://github.com/yujiading/fractals"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "~3.9"
pandas = "^1.4.0"
scipy = "^1.8.0"
tqdm = "^4.62.3"


[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
